### ISSUE TITLE
Evaluate performance returns non-positive ranks

### ISSUE THREAD

**Issue by tabacof** [Accenture/AmpliGraph#119]
### Description
Evaluate performance returns non-positive ranks.

### Actual Behavior
Six ranks out of ten thousand are non-positive in the attached example.

### Expected Behavior
Ranks should always be positive.

### Steps to Reproduce
Run attached notebook script: https://gist.github.com/tabacof/42c72b6e7b15df66584a4fd8ab770d06

Dataset: http://pages.cs.wisc.edu/~anhai/data/784_data/movies5.tar.gz

### Image

![image](https://user-images.githubusercontent.com/2151702/62051915-4a745380-b20c-11e9-936f-478290679e0c.png)

**Comment by sumitpai** [comment]
Can you please confirm if the x_filter had duplicate triples?

**Comment by tabacof** [comment]
![image](https://user-images.githubusercontent.com/2151702/62052657-d175fb80-b20d-11e9-965d-872fc1eefbe9.png)

**Comment by sumitpai** [comment]
I just verified. Actually there are 3 triples in X_valid that have duplicates in X_filter. Hence the ranks are <=0 for those 3 triples.
```
print(X_valid[np.logical_or(r[:,0]<=0, r[:,1]<=0),:])
```

Similarly in the entire dataset, there are 37 duplicates 
```
uniq_triples, counts = np.unique(filter_triples, 
                                 return_counts=True, 
                                 axis=0)
duplicate_triples = np.concatenate([uniq_triples[counts>1], 
                                    np.expand_dims(counts[counts>1],1)], 1)
print('Duplicates :', duplicate_triples.shape[0])
print(duplicate_triples)
```

It is because of the duplicates you are getting this issue. Ideally there should not be any duplicate statements in the graph. Since we do not have checks in place to verify the presence of duplicates, the rank computation logic gets affected.

**Comment by sumitpai** [comment]
I have modified the logic which subtracts the ranks of False Negatives that are generated by corruption generation in eval (when there are duplicate triples in the filter_triples). 

This fix assumes that the user may want to have duplicate triples in order to weigh a particular edge more than others in the graph. In such scenarios, the input may contain duplicate triples. But while evaluating, such duplicates must be treated as one triple (if the filter_triples contain such cases).
