### ISSUE TITLE
Evaluate performance is not idempotent

### ISSUE THREAD

**Issue by tabacof** [Accenture/AmpliGraph#120]
### Description
Evaluate performance changes the state of the model and sometimes there is no turning back.

### Actual Behavior
By calling evaluate performance many times, with and without filter_triples, with well formatted or badly formatted inputs, it will stop working after a specific combination of calls.

### Expected Behavior
Evaluate performance should be idempotent (i.e. always respond the same to the same input configuration).

### Steps to Reproduce
1. Run evaluate performance without filter triples with well formatted input
2. Run it again with badly formatted input and filter triples
3. Try (1)

Those are not exact steps, so maybe it is necessary to play around with the calls a bit before getting into the wrong state.

**Comment by sumitpai** [comment]
Just writing down what we discussed. This issue is due to the error that happens with badly formatted inputs (or any other exceptions that occur after the computational graph is built). 

The exception is not handled and the evaluation session is not reset. Hence when you go back to step 3, the computational graph remains the same (as created in step 2) which results in the error. 

We need to have general exception handling blocks at each entry points of the model and clear the states accordingly.
